### ISSUE TITLE
Certificate yaml unmarshaller

### ISSUE THREAD

**Issue by teodor-pripoae** [flanksource/commons#11]
Support multiple kinds of certificate definitions:

```go
type Config struct {
   CaCertificate certs.Certificate `yaml:"ca,omitempty"`
}
```

```yaml
ca:
   cert: "https://example.com/ca/cert"
   privateKey: "/path/to/cert"
   password: $CA_PASSWORD
```
